name: tba_api_client
version: 0.1.0
description: (Unofficial) Dart library for the TheBlueAlliance.com API
authors:
  - Aidan Mundy <amboyscout@aol.com>
homepage: https://github.com/aidan-mundy
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  http: ">=0.12.0 <0.13.0"
dev_dependencies:
  test: ^1.3.0
