name: tba_api_v3
version: 1.0.0
description: Unofficial Dart library for the TheBlueAlliance.com API
homepage: https://github.com/RobluScouting/Dart-TBA-API-Client
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: '>=4.0.0 <5.0.0'
  built_value: '>=8.0.4 <9.0.0'
  built_collection: '>=5.0.0 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.0.4 <9.0.0'
  build_runner: ^2.0.0
  test: '>=1.16.0 <1.17.0'
