name: tba_api_client
version: 0.2.1
description: (Unofficial) Dart library for the TheBlueAlliance.com API
authors:	
  - Aidan Mundy <amboyscout@aol.com>	
homepage: https://github.com/aidan-mundy
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  dio: ^3.0.9
  built_value: ^7.1.0
  built_collection: ^4.3.2
dev_dependencies:
  built_value_generator: ^7.1.0
  build_runner: ^1.7.1
